/**
 * Server-evaluation runtime for modules generated by the TSRX compiler.
 *
 * A generated server module re-declares the component's `@{ }` setup
 * verbatim, so the ambient identifiers the source relies on — signal
 * constructors and `expose()` — must resolve to server-side shims. On the
 * server a signal is its initial value in a box: `.get()` reads it once and
 * `.set()` is a no-op, because the server renders once and never reacts
 * (ADR 0023 sub-design 2: "signals as plain values").
 *
 * This module is imported by *generated* code (`server/generated/tsrx/`),
 * never by the compiler itself.
 */

/* === Types === */

/** Server-side stand-in for a Cause & Effect cell: read-once box, inert set. */
export type ServerCell<T> = {
	get: () => T
	set: (value: T) => void
}

/** Server-side stand-in for a `List`: iterates its seed, never mutates. */
export type ServerList<T> = ServerCell<T[]> & {
	[Symbol.iterator]: () => Iterator<T>
}

/* === Exported Functions === */

/** `createCell(initial)` → box over `initial`. */
export const createCell = <T>(initial: T): ServerCell<T> => ({
	get: () => initial,
	set: () => {},
})

/** `createList(seed, …)` → iterable box over the seed items. */
export const createList = <T>(seed: Iterable<T> = []): ServerList<T> => {
	const items = Array.from(seed)
	return {
		get: () => items,
		set: () => {},
		[Symbol.iterator]: () => items[Symbol.iterator](),
	}
}

/** `createStore(initial)` → box over `initial`. */
export const createStore = <T>(initial: T): ServerCell<T> => createCell(initial)

/** `deriveCell(fn)` → box over `fn()` evaluated once. */
export const deriveCell = <T>(compute: () => T): ServerCell<T> =>
	createCell(compute())

/** `deriveList(fn)` → list box over `fn()` evaluated once. */
export const deriveList = <T>(compute: () => Iterable<T>): ServerList<T> =>
	createList(compute())

/** `deriveStore(fn)` → box over `fn()` evaluated once. */
export const deriveStore = <T>(compute: () => T): ServerCell<T> =>
	deriveCell(compute)

/**
 * `expose()` records the client interface; on the server it is metadata
 * only — evaluating its argument object (which reads `.get()` once) is the
 * entire effect.
 */
export const expose = (_props: Record<string, unknown>): void => {}

/**
 * HTML-escape interpolated values — same semantics as the docs pipeline's
 * `escapeHtml` (server/templates/utils.ts).
 */
export const esc = (text: string): string =>
	text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;')

/**
 * Render one attribute from a computed value, matching `bindAttribute`'s
 * client dispatch (string → setAttribute, boolean → toggleAttribute,
 * number → String(v)):
 * - `true`  → ` name` (bare presence)
 * - `false` / `null` / `undefined` → nothing (omitted)
 * - number → ` name="3"` (numbers carry no HTML-escapable characters)
 * - string → ` name="escaped"`
 */
export const attr = (name: string, value: unknown): string => {
	if (value === true) return ` ${name}`
	if (value === false || value === null || value === undefined) return ''
	if (typeof value === 'number') return ` ${name}="${value}"`
	return ` ${name}="${esc(String(value))}"`
}

/** Render a class map's truthy keys as a class list (`{ a: true, b: x }` → `"a"`). */
export const cls = (map: Record<string, unknown>): string =>
	Object.entries(map)
		.filter(([, on]) => Boolean(on))
		.map(([token]) => token)
		.join(' ')

/** `@for` iteration helper over the items themselves (index unused). */
export const items = <T>(iterable: Iterable<T>): T[] => Array.from(iterable)

/** `@for` iteration helper: index/value pairs over any iterable. */
export const entries = <T>(
	iterable: Iterable<T>,
): IterableIterator<[number, T]> => Array.from(iterable).entries()
