/**
 * Server-evaluation runtime for modules generated by the TSRX compiler.
 *
 * A generated server module re-declares the component's `@{ }` setup
 * verbatim, so the ambient identifiers the source relies on — signal
 * constructors and `expose()` — must resolve to server-side shims. On the
 * server a signal is its initial value in a box: `.get()` reads it once and
 * `.set()` is a no-op, because the server renders once and never reacts
 * (ADR 0023 sub-design 2: "signals as plain values").
 *
 * This module is imported by *generated* code (`server/generated/tsrx/`),
 * never by the compiler itself.
 */

/* === Types === */

/** Server-side stand-in for a Cause & Effect cell: read-once box, inert set. */
export type ServerCell<T> = {
	get: () => T
	set: (value: T) => void
}

/** Server-side stand-in for a `List`: iterates its seed, never mutates. */
export type ServerList<T> = ServerCell<T[]> & {
	[Symbol.iterator]: () => Iterator<T>
	/** Key/value pairs mirroring cause-effect's keyConfig generation. */
	entries: () => Array<[string, T]>
}

/* === Exported Functions === */

/** `createCell(initial)` → box over `initial`. */
export const createCell = <T>(initial: T): ServerCell<T> => ({
	get: () => initial,
	set: () => {},
})

/**
 * `createList(seed, { keyConfig })` → iterable box over the seed items, with
 * key/value entries that mirror cause-effect's `getKeyGenerator` exactly
 * (string prefix → `prefix0…`, function → `fn(item) ?? auto`, none →
 * positional `0…`) — the server render's `data-key` values must match the
 * keys the client's real `createList` generates for the same seed, or
 * `reconcile()` adoption fails (ADR 0023 sub-design 3: one seeding story).
 */
export const createList = <T>(
	seed: Iterable<T> = [],
	options?: { keyConfig?: string | ((item: T) => string | undefined) },
): ServerList<T> => {
	const items = Array.from(seed)
	let keyCounter = 0
	const keyConfig = options?.keyConfig
	const keyOf = (item: T): string =>
		typeof keyConfig === 'string'
			? `${keyConfig}${keyCounter++}`
			: typeof keyConfig === 'function'
				? keyConfig(item) || String(keyCounter++)
				: String(keyCounter++)
	const keyed = items.map(item => [keyOf(item), item] as [string, T])
	return {
		get: () => items,
		set: () => {},
		[Symbol.iterator]: () => items[Symbol.iterator](),
		entries: () => keyed,
	}
}

/** `createStore(initial)` → box over `initial`. */
export const createStore = <T>(initial: T): ServerCell<T> => createCell(initial)

/** `createState(initial)` → same box as createCell (the v2 name). */
export const createState = <T>(initial: T): ServerCell<T> => createCell(initial)

/** `deriveCell(fn)` → box over `fn()` evaluated once. */
export const deriveCell = <T>(compute: () => T): ServerCell<T> =>
	createCell(compute())

/** `deriveList(fn)` → list box over `fn()` evaluated once. */
export const deriveList = <T>(compute: () => Iterable<T>): ServerList<T> =>
	createList(compute())

/** `deriveStore(fn)` → box over `fn()` evaluated once. */
export const deriveStore = <T>(compute: () => T): ServerCell<T> =>
	deriveCell(compute)

/**
 * `expose()` records the client interface; on the server it is metadata
 * only — evaluating its argument object (which reads `.get()` once) is the
 * entire effect.
 */
export const expose = (_props: Record<string, unknown>): void => {}

/**
 * `defineMethod(fn)` — identity on the server: the branded MethodProducer
 * matters only to the client's `expose()` dispatch, and the method body is
 * never invoked during server evaluation.
 */
export const defineMethod = <T extends (...args: unknown[]) => void>(
	fn: T,
): T => fn

/**
 * Parser-factory shims (`asString` etc.). The verbatim setup calls them when
 * `expose()` carries Parser-backed attribute-driven props (ADR 0023
 * sub-design 8); their results are metadata on the server — the real parsers
 * run in the browser at connect time against the host attribute (ADR 0003).
 */
export const asString =
	(fallback: string = '') =>
	(value: string | null | undefined): string =>
		value ?? fallback

export const asInteger =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? Math.trunc(n) : fallback
	}

export const asNumber =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? n : fallback
	}

export const asBoolean =
	(fallback: boolean = false) =>
	(value: string | null | undefined): boolean =>
		value == null ? fallback : value !== 'false'

export const asEnum =
	(valid: readonly [string, ...string[]]) =>
	(value: string | null | undefined): string =>
		valid.includes(value as string) ? (value as string) : valid[0]

/** Clamped-integer shim mirroring src/parsers/number.ts (min/max clamp). */
export const asClampedInteger =
	(min: number = 0, max: number = Number.MAX_SAFE_INTEGER) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		const parsed = value != null && Number.isFinite(n) ? Math.trunc(n) : min
		return Math.max(min, Math.min(parsed, max))
	}

/** JSON shim mirroring src/parsers/json.ts (fallback on null/unparseable). */
export const asJSON =
	<T extends {}>(fallback: T) =>
	(value: string | null | undefined): T => {
		if (value == null || value === '') return fallback
		try {
			return JSON.parse(value) as T
		} catch {
			return fallback
		}
	}

/**
 * HTML-escape interpolated values — same semantics as the docs pipeline's
 * `escapeHtml` (server/templates/utils.ts).
 */
export const esc = (text: string): string =>
	text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;')

/**
 * Render one attribute from a computed value, matching `bindAttribute`'s
 * client dispatch (string → setAttribute, boolean → toggleAttribute,
 * number → String(v)):
 * - `true`  → ` name` (bare presence)
 * - `false` / `null` / `undefined` → nothing (omitted)
 * - number → ` name="3"` (numbers carry no HTML-escapable characters)
 * - string → ` name="escaped"`
 */
export const attr = (name: string, value: unknown): string => {
	if (value === true) return ` ${name}`
	if (value === false || value === null || value === undefined) return ''
	if (typeof value === 'number') return ` ${name}="${value}"`
	return ` ${name}="${esc(String(value))}"`
}

/**
 * Render a class map's truthy keys as a class list (`{ a: true, b: x }` → `"a"`).
 */
export const cls = (map: Record<string, unknown>): string =>
	Object.entries(map)
		.filter(([, on]) => Boolean(on))
		.map(([token]) => token)
		.join(' ')

/**
 * Sanitize trusted-build-time HTML for the `html={expr}` dynamic-rendering
 * attribute (defense-in-depth, mirroring `setAttribute`'s own posture in
 * the library): strip script blocks, event-handler attributes, and unsafe
 * URL schemes (javascript:/vbscript:/data: except data:image). The input is
 * authored markup (docs content), not arbitrary user input — this catches
 * the common footguns rather than replacing a real sanitizer.
 */
export const sanitizeHtml = (html: string): string => {
	let current = html
	let next: string
	do {
		next = current
			.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi, '')
			.replace(/<script\b[^>]*\/?>/gi, '')
			.replace(/\son[a-z]+\s*=\s*"[^"]*"/gi, '')
			.replace(/\son[a-z]+\s*=\s*'[^']*'/gi, '')
			.replace(/\son[a-z]+\s*=[^\s>]+/gi, '')
			.replace(
				/\s(href|src|action|formaction|xlink:href)\s*=\s*(["'])\s*(javascript|vbscript|data(?!:image\/(png|gif|jpeg|jpg|webp|svg\+xml)):)[^"']*\2/gi,
				'',
			)
		if (next === current) break
		current = next
	} while (true)
	return current
}

/** `@for` iteration helper over the items themselves (index unused). */
export const items = <T>(iterable: Iterable<T>): T[] => Array.from(iterable)

/** `@for` iteration helper: index/value pairs over any iterable. */
export const entries = <T>(
	iterable: Iterable<T>,
): IterableIterator<[number, T]> => Array.from(iterable).entries()
