/**
 * Server-evaluation runtime for modules generated by the TSRX compiler.
 *
 * A generated server module re-declares the component's `@{ }` setup
 * verbatim, so the ambient identifiers the source relies on — signal
 * constructors and `expose()` — must resolve to server-side shims. On the
 * server a signal is its initial value in a box: `.get()` reads it once and
 * `.set()` is a no-op, because the server renders once and never reacts
 * (ADR 0023 sub-design 2: "signals as plain values").
 *
 * This module is imported by *generated* code (`server/generated/tsrx/`),
 * never by the compiler itself.
 */

/* === Types === */

/** Server-side stand-in for a Cause & Effect cell: read-once box, inert set. */
export type ServerCell<T> = {
	get: () => T
	set: (value: T) => void
}

/** Server-side stand-in for a `List`: iterates its seed, never mutates. */
export type ServerList<T> = ServerCell<T[]> & {
	[Symbol.iterator]: () => Iterator<T>
	/** Key/value pairs mirroring cause-effect's keyConfig generation. */
	entries: () => Array<[string, T]>
}

/* === Exported Functions === */

/** `createCell(initial)` → box over `initial`. */
export const createCell = <T>(initial: T): ServerCell<T> => ({
	get: () => initial,
	set: () => {},
})

/**
 * `createList(seed, { keyConfig })` → iterable box over the seed items, with
 * key/value entries that mirror cause-effect's `getKeyGenerator` exactly
 * (string prefix → `prefix0…`, function → `fn(item) ?? auto`, none →
 * positional `0…`) — the server render's `data-key` values must match the
 * keys the client's real `createList` generates for the same seed, or
 * `reconcile()` adoption fails (ADR 0023 sub-design 3: one seeding story).
 */
export const createList = <T>(
	seed: Iterable<T> = [],
	options?: { keyConfig?: string | ((item: T) => string | undefined) },
): ServerList<T> => {
	const items = Array.from(seed)
	let keyCounter = 0
	const keyConfig = options?.keyConfig
	const keyOf = (item: T): string =>
		typeof keyConfig === 'string'
			? `${keyConfig}${keyCounter++}`
			: typeof keyConfig === 'function'
				? keyConfig(item) || String(keyCounter++)
				: String(keyCounter++)
	const keyed = items.map(item => [keyOf(item), item] as [string, T])
	return {
		get: () => items,
		set: () => {},
		[Symbol.iterator]: () => items[Symbol.iterator](),
		entries: () => keyed,
	}
}

/** `createStore(initial)` → box over `initial`. */
export const createStore = <T>(initial: T): ServerCell<T> => createCell(initial)

/** `createState(initial)` → same box as createCell (the v2 name). */
export const createState = <T>(initial: T): ServerCell<T> => createCell(initial)

/**
 * Marks a `ServerCell` as pending (ADR 0023 sub-design 13, async boundaries,
 * LT-012) — never exposed on the type; `isPending` is the only sanctioned way
 * to read it.
 */
const ASYNC_PENDING = Symbol('tsrx-async-pending')

/** Runtime check for an `async` function, without invoking it. */
const isAsyncFunction = (fn: (...args: never[]) => unknown): boolean =>
	(fn as { constructor?: { name?: string } })?.constructor?.name ===
	'AsyncFunction'

/**
 * `deriveCell(fn, options?)` → box over `fn()` evaluated once, UNLESS `fn` is
 * an `async` function (ADR 0023 sub-design 13): the server render is
 * synchronous and never awaits, so an async compute is never invoked at
 * all — calling it would produce a dangling, uncaught Promise. Instead: an
 * `{ initial }` option seeds the retained value directly (the `ok` arm,
 * matching the client's own no-JS-safe seed); otherwise the cell is PENDING
 * at render time (the `nil`/`@pending` arm) — `.get()` throws if read without
 * an `isPending()` guard, same contract a real Task-backed cell enforces.
 * A SYNC compute function's behavior is completely unchanged from before
 * this feature landed — existing non-async `deriveCell` usage (e.g. a
 * `description` memo) is unaffected.
 */
export const deriveCell = <T>(
	compute: () => T | Promise<T>,
	options?: { initial?: T },
): ServerCell<T> => {
	if (!isAsyncFunction(compute as (...args: never[]) => unknown))
		return createCell(compute() as T)
	if (options && 'initial' in options) return createCell(options.initial as T)
	return {
		get: () => {
			throw new Error(
				'deriveCell(...) is pending (no { initial } seed) — read it only inside an isPending()-guarded branch (ADR 0023 async boundaries).',
			)
		},
		set: () => {},
		[ASYNC_PENDING]: true,
	} as ServerCell<T>
}

/**
 * Whether an async-derived cell is pending at render time (ADR 0023 sub-
 * design 13) — `@try`/`@pending`/`@catch` async boundaries route on this,
 * mirroring `@zeix/cause-effect`'s real `isPending()` behaviorally (a
 * different underlying representation server-side, since the server shim
 * never runs the reactive graph).
 */
export const isPending = (signal: unknown): boolean =>
	!!signal &&
	typeof signal === 'object' &&
	(signal as Record<symbol, unknown>)[ASYNC_PENDING] === true

/**
 * `createMemo(fn, options?)` → box over `fn(prev)` evaluated once. Unlike
 * `deriveCell`, `createMemo` has no async overload (cause-effect's `Memo`
 * type is sync-only), so there is no pending-render branch to consider —
 * `options.value` seeds the reducer-pattern `prev` argument on this single
 * server-side call, exactly as it seeds the client's first computation.
 */
export const createMemo = <T>(
	compute: (prev: T | undefined) => T,
	options?: { value?: T },
): ServerCell<T> => createCell(compute(options?.value))

/** `deriveList(fn)` → list box over `fn()` evaluated once. */
export const deriveList = <T>(compute: () => Iterable<T>): ServerList<T> =>
	createList(compute())

/** `deriveStore(fn)` → box over `fn()` evaluated once. */
export const deriveStore = <T>(compute: () => T): ServerCell<T> =>
	deriveCell(compute)

/**
 * `expose()` records the client interface; on the server it is metadata
 * only — evaluating its argument object (which reads `.get()` once) is the
 * entire effect.
 */
export const expose = (_props: Record<string, unknown>): void => {}

/**
 * `defineMethod(fn)` — identity on the server: the branded MethodProducer
 * matters only to the client's `expose()` dispatch, and the method body is
 * never invoked during server evaluation.
 */
export const defineMethod = <T extends (...args: unknown[]) => void>(
	fn: T,
): T => fn

/**
 * Parser-factory shims (`asString` etc.). The verbatim setup calls them when
 * `expose()` carries Parser-backed attribute-driven props (ADR 0023
 * sub-design 8); their results are metadata on the server — the real parsers
 * run in the browser at connect time against the host attribute (ADR 0003).
 */
export const asString =
	(fallback: string = '') =>
	(value: string | null | undefined): string =>
		value ?? fallback

export const asInteger =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? Math.trunc(n) : fallback
	}

export const asNumber =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? n : fallback
	}

export const asBoolean =
	(fallback: boolean = false) =>
	(value: string | null | undefined): boolean =>
		value == null ? fallback : value !== 'false'

export const asEnum =
	(valid: readonly [string, ...string[]]) =>
	(value: string | null | undefined): string =>
		valid.includes(value as string) ? (value as string) : valid[0]

/** Clamped-integer shim mirroring src/parsers/number.ts (min/max clamp). */
export const asClampedInteger =
	(min: number = 0, max: number = Number.MAX_SAFE_INTEGER) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		const parsed = value != null && Number.isFinite(n) ? Math.trunc(n) : min
		return Math.max(min, Math.min(parsed, max))
	}

/** JSON shim mirroring src/parsers/json.ts (fallback on null/unparseable). */
export const asJSON =
	<T extends {}>(fallback: T) =>
	(value: string | null | undefined): T => {
		if (value == null || value === '') return fallback
		try {
			return JSON.parse(value) as T
		} catch {
			return fallback
		}
	}

/**
 * HTML-escape interpolated values — same semantics as the docs pipeline's
 * `escapeHtml` (server/templates/utils.ts).
 */
export const esc = (text: string): string =>
	text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;')

/**
 * Render one attribute from a computed value, matching `bindAttribute`'s
 * client dispatch (string → setAttribute, boolean → toggleAttribute,
 * number → String(v)):
 * - `true`  → ` name` (bare presence)
 * - `false` / `null` / `undefined` → nothing (omitted)
 * - number → ` name="3"` (numbers carry no HTML-escapable characters)
 * - string → ` name="escaped"`
 */
export const attr = (name: string, value: unknown): string => {
	if (value === true) return ` ${name}`
	if (value === false || value === null || value === undefined) return ''
	if (typeof value === 'number') return ` ${name}="${value}"`
	return ` ${name}="${esc(String(value))}"`
}

/**
 * Render a class map's truthy keys as a class list (`{ a: true, b: x }` → `"a"`).
 */
export const cls = (map: Record<string, unknown>): string =>
	Object.entries(map)
		.filter(([, on]) => Boolean(on))
		.map(([token]) => token)
		.join(' ')

/**
 * Render a style map's non-nil entries as an inline style declaration list
 * (`{ color: 'red', '--x': null }` → `"color: red"`), matching `bindStyle()`'s
 * map-form client dispatch (LT-028, LT-029): a `null`/`undefined` value is
 * omitted, same as `removeProperty` on the client. Returns `''` when every
 * entry is nil.
 */
export const styleAttr = (
	map: Record<string, string | null | undefined>,
): string =>
	Object.entries(map)
		.filter(([, v]) => v != null)
		.map(([prop, v]) => `${prop}: ${v}`)
		.join('; ')

/**
 * The sanitizer applied to every `html={expr}` dynamic-rendering attribute
 * across the whole compiled site. Defaults to escaping all markup (safe but
 * inert — `<` and `>` become entities, so no element ever renders) until a
 * host configures a real sanitizer via `configureHtmlSanitizer`, mirroring
 * the client's `dangerouslyBindInnerHTML` `sanitize` hook (ADR 0010):
 * the library — here, the generated server module — owns no sanitizer,
 * the consumer supplies one appropriate to their trust level (e.g. DOMPurify).
 */
let htmlSanitizer: (html: string) => string = html =>
	html.replace(/</g, '&lt;').replace(/>/g, '&gt;')

/**
 * Configure the sanitizer used by `sanitizeHtml` for every `html={expr}`
 * dynamic-rendering attribute in the compiled site. Call once at server
 * startup, before any generated module renders.
 */
export const configureHtmlSanitizer = (sanitizer: (html: string) => string) => {
	htmlSanitizer = sanitizer
}

/**
 * Sanitize HTML for the `html={expr}` dynamic-rendering attribute by
 * delegating to the configured sanitizer (see `configureHtmlSanitizer`).
 */
export const sanitizeHtml = (html: string): string => htmlSanitizer(html)

/** `@for` iteration helper over the items themselves (index unused). */
export const items = <T>(iterable: Iterable<T>): T[] => Array.from(iterable)

/** `@for` iteration helper: index/value pairs over any iterable. */
export const entries = <T>(
	iterable: Iterable<T>,
): IterableIterator<[number, T]> => Array.from(iterable).entries()
