// Le Truc 2.6.0

// From Cause & Effect
// Names deprecated by @zeix/cause-effect 1.5 ahead of its 2.0 keep their upstream
// @deprecated markers through these re-exports; the v2 bridge names are re-exported
// alongside them so consumers can migrate via CE's MIGRATION-2.0.md.
export {
	abort,
	batch,
	type Cell,
	CircularDependencyError,
	type Cleanup,
	type Collection,
	type CollectionChanges,
	type CollectionOptions,
	type ComputedOptions,
	createCell,
	createCollection,
	createComputed,
	createEffect,
	createList,
	createMemo,
	createMutableSignal,
	createScope,
	createSensor,
	createSignal,
	createSlot,
	createState,
	createStore,
	createTask,
	DEEP_EQUALITY,
	DEFAULT_EQUALITY,
	type DeriveCellOptions,
	type DerivedList,
	type DerivedStore,
	type DeriveListOptions,
	type DeriveSignalOptions,
	type DeriveStoreOptions,
	DuplicateKeyError,
	deriveCell,
	deriveList,
	deriveSignal,
	deriveStore,
	type EffectCallback,
	EffectConvergenceError,
	type Guard,
	InvalidCallbackError,
	InvalidSignalValueError,
	InvalidStoreMutationError,
	isAsyncFunction,
	isCell,
	isCollection,
	isComputed,
	isDerivedList,
	isFunction,
	isList,
	isMemo,
	isMutableCell,
	isMutableList,
	isMutableSignal,
	isMutableStore,
	isPending,
	isRecord,
	isSensor,
	isSignal,
	isSignalOfType,
	isSlot,
	isState,
	isStore,
	isTask,
	type List,
	type ListCallback,
	type ListChanges,
	type ListOptions,
	type ListSource,
	type MatchHandlers,
	type MaybeCleanup,
	type MaybePromise,
	type Memo,
	type MemoCallback,
	type MutableCell,
	type MutableList,
	type MutableSignal,
	type MutableStore,
	match,
	NullishSignalValueError,
	type PerItemCallback,
	PromiseValueError,
	ReadonlySignalError,
	RequiredOwnerError,
	type ScopeOptions,
	type Sensor,
	type SensorOptions,
	type Signal,
	type SignalOptions,
	type SingleMatchHandlers,
	SKIP_EQUALITY,
	type Slot,
	type SlotDescriptor,
	type State,
	type Store,
	type StoreCallback,
	type StoreOptions,
	type Task,
	type TaskCallback,
	UnresolvableKeyError,
	UnsetSignalValueError,
	unown,
	untrack,
} from '@zeix/cause-effect'

export {
	bindAttribute,
	bindClass,
	bindProperty,
	bindState,
	bindStyle,
	bindText,
	bindVisible,
	type DangerouslyBindInnerHTMLOptions,
	dangerouslyBindInnerHTML,
	escapeHTML,
	safeSetAttribute,
	setTextPreservingComments,
} from './src/bindings'
export {
	defineComponent,
	type FactoryContext,
	type FormAssociatedElement,
	type Initializers,
	type MaybeSignal,
} from './src/component'
export {
	DependencyTimeoutError,
	ExtensionCollisionError,
	InvalidComponentNameError,
	InvalidCustomElementError,
	InvalidPassPropertyError,
	InvalidPropertyNameError,
	InvalidReactivesError,
	InvalidSelectorError,
	InvalidTemplateError,
	MissingElementError,
	NoActiveCollectorError,
} from './src/errors'
export { type ComponentExtension } from './src/extension'
export { observedAttributes } from './src/extensions/attributes'
export {
	type FormAssociatedCheckboxExtension,
	type FormAssociatedExtension,
	formAssociated,
	formAssociatedCheckbox,
	relayValidity,
	type ValidatableControl,
} from './src/extensions/form'
export {
	CONTEXT_REQUEST,
	type Context,
	type ContextCallback,
	ContextRequestEvent,
	type ContextType,
	createContext,
	type ProvideContextsHelper,
	type RequestContextHelper,
	type UnknownContext,
} from './src/helpers/context'
export {
	type AllElements,
	createElementsMemo,
	type ElementFromSelector,
	type ElementFromSingleSelector,
	type ElementQueries,
	type ElementsFromSelectorArray,
	type ExtractRightmostSelector,
	type ExtractTag,
	type ExtractTagFromSimpleSelector,
	type FirstElement,
	type KnownTag,
	query,
	queryAll,
	type SplitByComma,
	type TrimWhitespace,
} from './src/helpers/dom'
export type { EventType, OnEventHandler, OnHelper } from './src/helpers/events'
export {
	each,
	type PassedProps,
	type PassHelper,
	type Reactive,
	reconcile,
	type WatchHelper,
} from './src/helpers/reactive'
export { asBoolean } from './src/parsers/boolean'
export { asJSON } from './src/parsers/json'
export { asClampedInteger, asInteger, asNumber } from './src/parsers/number'
export { asEnum, asString } from './src/parsers/string'
export { schedule, throttle } from './src/scheduler'
export {
	asParser,
	type ComponentProp,
	type ComponentProps,
	defineMethod,
	type EffectDescriptor,
	type FactoryResult,
	type Falsy,
	isMethodProducer,
	isParser,
	type MethodProducer,
	type Parser,
	type ReservedWords,
} from './src/types'
