// Le Truc 2.0.1

// From Cause & Effect
export {
	batch,
	CircularDependencyError,
	type Cleanup,
	type Collection,
	type CollectionChanges,
	type CollectionOptions,
	type ComputedOptions,
	createCollection,
	createComputed,
	createEffect,
	createList,
	createMemo,
	createMutableSignal,
	createScope,
	createSensor,
	createSignal,
	createSlot,
	createState,
	createStore,
	createTask,
	DEEP_EQUALITY,
	DEFAULT_EQUALITY,
	type EffectCallback,
	type Guard,
	InvalidCallbackError,
	InvalidSignalValueError,
	isAsyncFunction,
	isCollection,
	isComputed,
	isFunction,
	isList,
	isMemo,
	isMutableSignal,
	isRecord,
	isSensor,
	isSignal,
	isSignalOfType,
	isSlot,
	isState,
	isStore,
	isTask,
	type List,
	type ListOptions,
	type MatchHandlers,
	type MaybeCleanup,
	type MaybePromise,
	type Memo,
	type MemoCallback,
	match,
	NullishSignalValueError,
	ReadonlySignalError,
	RequiredOwnerError,
	type ScopeOptions,
	type Sensor,
	type SensorOptions,
	type Signal,
	type SignalOptions,
	type SingleMatchHandlers,
	SKIP_EQUALITY,
	type Slot,
	type SlotDescriptor,
	type State,
	type Store,
	type StoreOptions,
	type Task,
	type TaskCallback,
	UnsetSignalValueError,
	unown,
	untrack,
	valueString,
} from '@zeix/cause-effect'

export {
	defineComponent,
	type FactoryContext,
	type Initializers,
	type MaybeSignal,
} from './src/component'
export {
	CONTEXT_REQUEST,
	type Context,
	type ContextCallback,
	ContextRequestEvent,
	type ContextType,
	type ProvideContextsHelper,
	type RequestContextHelper,
	type UnknownContext,
} from './src/helpers/context'
export {
	each,
	type PassedProps,
	type PassHelper,
	type Reactive,
	type WatchHelper,
} from './src/helpers/reactive'
export {
	DependencyTimeoutError,
	InvalidComponentNameError,
	InvalidCustomElementError,
	InvalidPropertyNameError,
	InvalidReactivesError,
	MissingElementError,
} from './src/errors'
export type { EventType, OnEventHandler, OnHelper } from './src/helpers/events'
export {
	bindAttribute,
	bindClass,
	bindProperty,
	bindStyle,
	bindText,
	bindVisible,
	type DangerouslyBindInnerHTMLOptions,
	dangerouslyBindInnerHTML,
	escapeHTML,
	safeSetAttribute,
	setTextPreservingComments,
} from './src/bindings'
export {
	asParser,
	type ComponentProp,
	type ComponentProps,
	defineMethod,
	type EffectDescriptor,
	type FactoryResult,
	type Falsy,
	isMethodProducer,
	isParser,
	type MethodProducer,
	type Parser,
	type ReservedWords,
} from './src/types'
export { asBoolean } from './src/parsers/boolean'
export { asJSON } from './src/parsers/json'
export { asClampedInteger, asInteger, asNumber } from './src/parsers/number'
export { asEnum, asString } from './src/parsers/string'
export { schedule, throttle } from './src/scheduler'
export {
	type AllElements,
	createElementsMemo,
	type ElementFromSelector,
	type ElementFromSingleSelector,
	type ElementQueries,
	type ElementsFromSelectorArray,
	type ExtractRightmostSelector,
	type ExtractTag,
	type ExtractTagFromSimpleSelector,
	type FirstElement,
	type KnownTag,
	type SplitByComma,
	type TrimWhitespace,
} from './src/helpers/dom'
