// Le Truc 1.0.1

// From Cause & Effect
export {
	batch,
	CircularDependencyError,
	type Cleanup,
	type Collection,
	type CollectionChanges,
	type CollectionOptions,
	type ComputedOptions,
	createCollection,
	createComputed,
	createEffect,
	createList,
	createMemo,
	createMutableSignal,
	createScope,
	createSensor,
	createSignal,
	createSlot,
	createState,
	createStore,
	createTask,
	type EffectCallback,
	type Guard,
	InvalidCallbackError,
	InvalidSignalValueError,
	isAsyncFunction,
	isCollection,
	isComputed,
	isEqual,
	isFunction,
	isList,
	isMemo,
	isMutableSignal,
	isObjectOfType,
	isRecord,
	isSensor,
	isSignal,
	isSlot,
	isState,
	isStore,
	isTask,
	type List,
	type ListOptions,
	type MatchHandlers,
	type MaybeCleanup,
	type Memo,
	type MemoCallback,
	match,
	NullishSignalValueError,
	ReadonlySignalError,
	RequiredOwnerError,
	type Sensor,
	type SensorOptions,
	type Signal,
	type SignalOptions,
	SKIP_EQUALITY,
	type Slot,
	type State,
	type Store,
	type StoreOptions,
	type Task,
	type TaskCallback,
	UnsetSignalValueError,
	unown,
	untrack,
	valueString,
} from '@zeix/cause-effect'

export {
	type Component,
	type ComponentProp,
	type ComponentProps,
	type ComponentSetup,
	type ComponentUI,
	defineComponent,
	type FactoryContext,
	type FactoryOnHelper,
	type FactoryPassHelper,
	type FactoryProvideContextsHelper,
	type FactoryRequestContextHelper,
	type FactoryWatchHelper,
	type Initializers,
	type MaybeSignal,
	type ReservedWords,
} from './src/component'
export {
	CONTEXT_REQUEST,
	type Context,
	type ContextCallback,
	ContextRequestEvent,
	type ContextType,
	type UnknownContext,
} from './src/context'
export {
	type EffectDescriptor,
	each,
	type FactoryResult,
} from './src/effects'
export { type PassedProp, type PassedProps } from './src/factory'
export {
	DependencyTimeoutError,
	InvalidComponentNameError,
	InvalidCustomElementError,
	InvalidEffectsError,
	InvalidPropertyNameError,
	InvalidReactivesError,
	InvalidUIKeyError,
	MissingElementError,
} from './src/errors'
export {
	createEventsSensor,
	type EventHandlers,
	type EventHandlersV2,
	type SensorEventHandler,
	type SensorEventHandlerV2,
} from './src/events'
export {
	asMethod,
	asParser,
	type Fallback,
	isMethodProducer,
	isParser,
	type LooseReader,
	type MethodProducer,
	type Parser,
	type ParserOrFallback,
	type Reader,
	read,
} from './src/parsers'
export { asBoolean } from './src/parsers/boolean'
export { asJSON } from './src/parsers/json'
export { asClampedInteger, asInteger, asNumber } from './src/parsers/number'
export { asDate } from './src/parsers/date'
export { asEnum, asString } from './src/parsers/string'
export {
	escapeHTML,
	safeSetAttribute,
	setTextPreservingComments,
} from './src/safety'
export {
	bindAttribute,
	bindClass,
	dangerouslySetInnerHTML,
	type DangerouslySetInnerHTMLOptions,
	bindProperty,
	bindStyle,
	bindText,
	bindVisible,
} from './src/helpers'
export { schedule } from './src/scheduler'
export {
	type AllElements,
	createElementsMemo,
	type ElementFromKey,
	type ElementFromSelector,
	type ElementFromSingleSelector,
	type ElementQueries,
	type ElementsFromSelectorArray,
	type ExtractRightmostSelector,
	type ExtractTag,
	type ExtractTagFromSimpleSelector,
	type FirstElement,
	type KnownTag,
	type SplitByComma,
	type TrimWhitespace,
	type UI,
} from './src/ui'
