/**
 * Server-evaluation runtime for modules generated by the TSRX compiler.
 *
 * A generated server module re-declares the component's `@{ }` setup
 * verbatim, so the ambient identifiers the source relies on — signal
 * constructors and `expose()` — must resolve to server-side shims. On the
 * server a signal is its initial value in a box: `.get()` reads it once and
 * `.set()` is a no-op, because the server renders once and never reacts
 * (ADR 0024 sub-design 2: "signals as plain values").
 *
 * This module is imported by *generated* code (`server/generated/components/`),
 * never by the compiler itself.
 */

import { sanitizeHtml as librarySanitizeHtml } from '../../src/bindings'
import { bakeMessageEnv, type Message, type MessageEnv } from './icu/evaluate'

/* === Re-exports === */

/**
 * The shared ICU evaluator (LT-250, ADR 0030 s4): the generated `i18n`
 * module wraps each argument message's parsed AST in a call to it, so the
 * server fold runs the same walk LT-218 inlines into the client.
 */
export {
	formatMessage,
	type Message,
	type MessageArgs,
	type MessageEnv,
} from './icu/evaluate'

/**
 * Where the generated `i18n` module keeps an argument message's parsed AST
 * on the closure `t.<key>` resolves to (LT-218). The server fold only ever
 * calls the closure; `clientMessages` reads the AST back to serialize it
 * into the client channel. A symbol, so it never shows up in `t`'s type or
 * in a spread.
 */
export const CLIENT_MESSAGE: unique symbol = Symbol.for(
	'le-truc.client-message',
)

/** What {@link CLIENT_MESSAGE} holds: the AST and the record it formats against. */
export type ClientMessageSource = { message: Message; env: MessageEnv }

/* === Types === */

/** Server-side stand-in for a Cause & Effect cell: read-once box, inert set. */
export type ServerCell<T> = {
	get: () => T
	set: (value: T) => void
}

/**
 * The signal the harness hands out for a value inside a store, mirroring
 * Cause & Effect's `MutableStore` field rule: an array is a list, a plain
 * object is a store, anything else is a cell.
 */
export type ServerFieldSignal<V> = V extends readonly (infer U)[]
	? ServerList<U>
	: V extends Record<string, unknown>
		? ServerStore<V>
		: ServerCell<V>

/**
 * Server-side stand-in for a `MutableStore` (ADR 0046 s3): every field is a
 * signal ({@link ServerFieldSignal}), and `get()` returns the whole value.
 */
export type ServerStore<T extends Record<string, unknown>> = ServerCell<T> & {
	readonly [K in keyof T]: ServerFieldSignal<T[K]>
}

/**
 * Server-side stand-in for a `List` (ADR 0046 s3, s4): iterates the item
 * CELLS it hands out — `S` is the `createItem` result, a cell by default —
 * keyed exactly as Cause & Effect keys the same seed. `get()` returns the
 * plain values. Never mutates.
 */
export type ServerList<T, S = ServerCell<T>> = ServerCell<T[]> & {
	readonly length: number
	[Symbol.iterator]: () => Iterator<S>
	at: (index: number) => S | undefined
	keys: () => IterableIterator<string>
	byKey: (key: string) => S | undefined
	/** `(cell, key)` per item, in order — a plain array, like C&E's `map`. */
	map: <R>(callback: (cell: S, key: string) => R) => R[]
	forEach: (callback: (cell: S, key: string) => void) => void
	/**
	 * `[key, cell]` pairs, for the emitted server loop only — not part of
	 * the authored vocabulary (C&E lists have no `entries()`).
	 */
	entries: () => Array<[string, S]>
}

/** Key configuration as Cause & Effect's `KeyConfig` accepts it. */
type KeyConfig<T> = string | ((item: T) => string | undefined)

/** Options the harness honors on `createList`/`deriveList`. */
type ServerListOptions<T, S> = {
	keyConfig?: KeyConfig<T>
	/**
	 * The authored factory's return is the CLIENT type the authored generic
	 * pins (`MutableStore<T>`, ADR 0046 s3) — the harness cannot implement
	 * the mutation half, so its own `createStore` is admitted through the
	 * union and the iteration keeps the authored `S`. The server render
	 * reads fields and never mutates, so the reduced stand-in carries every
	 * read the render makes.
	 */
	createItem?: (
		value: T,
	) => S | (T extends Record<string, unknown> ? ServerStore<T> : never)
}

/* === Exported Functions === */

/** `createCell(initial)` → box over `initial`. */
export const createCell = <T>(initial: T): ServerCell<T> => ({
	get: () => initial,
	set: () => {},
})

/**
 * `createList(seed, { keyConfig, createItem })` → a list over one cell per
 * seed item (`createItem`'s result, else a {@link createCell} box), with
 * keys that mirror cause-effect's `getKeyGenerator` exactly (string prefix
 * → `prefix0…`, function → `fn(item) || auto`, none → positional `0…`) —
 * the server render's `data-key` values must match the keys the client's
 * real `createList` generates for the same seed, or `reconcile()` adoption
 * fails (ADR 0024 sub-design 3: one seeding story).
 */
export const createList = <T, S = ServerCell<T>>(
	seed: Iterable<T> = [],
	options?: ServerListOptions<T, S>,
): ServerList<T, S> => {
	const items = Array.from(seed)
	let keyCounter = 0
	const keyConfig = options?.keyConfig
	const keyOf = (item: T): string =>
		typeof keyConfig === 'string'
			? `${keyConfig}${keyCounter++}`
			: typeof keyConfig === 'function'
				? keyConfig(item) || String(keyCounter++)
				: String(keyCounter++)
	const createItem =
		options?.createItem ?? ((value: T) => createCell(value) as S)
	const keyed = items.map(
		item => [keyOf(item), createItem(item)] as [string, S],
	)
	const cells = keyed.map(([, cell]) => cell)
	const byKey = new Map(keyed)
	return {
		get: () => items,
		set: () => {},
		length: items.length,
		[Symbol.iterator]: () => cells[Symbol.iterator](),
		at: index => cells.at(index),
		keys: () => byKey.keys(),
		byKey: key => byKey.get(key),
		map: callback => keyed.map(([key, cell]) => callback(cell, key)),
		forEach: callback => {
			for (const [key, cell] of keyed) callback(cell, key)
		},
		entries: () => keyed,
	}
}

/** Cause & Effect's `isRecord`: a plain object, the only kind a store nests. */
const isRecord = (value: unknown): value is Record<string, unknown> =>
	value !== null &&
	typeof value === 'object' &&
	Object.getPrototypeOf(value) === Object.prototype

/** The signal for one store field, by C&E's `MutableStore` rule. */
const fieldSignal = (value: unknown): unknown =>
	Array.isArray(value)
		? createList(value)
		: isRecord(value)
			? createStore(value)
			: createCell(value)

/**
 * `createStore(initial)` → a store whose fields are signals (nested objects
 * stores, arrays lists, anything else cells) and whose `get()` returns the
 * whole value — so `item.label.get()` runs at render time, as it does on the
 * client (ADR 0046 s3).
 */
export const createStore = <T extends Record<string, unknown>>(
	initial: T,
): ServerStore<T> => {
	const store: Record<string, unknown> = {}
	for (const [key, value] of Object.entries(initial))
		store[key] = fieldSignal(value)
	store.get = () => initial
	store.set = () => {}
	return store as ServerStore<T>
}

/**
 * `createSensor(start, { value })` → box over the `value` seed, its server
 * value (ADR 0046 s5). `start` subscribes to a client source and never runs
 * here. Unseeded, a sensor has no server value: the compiler routes every
 * read of one as unresolvable, so this `get()` throwing is only a backstop
 * against a read that analysis missed.
 */
export const createSensor = <T>(
	_start: (set: (value: T) => void) => () => void,
	options?: { value?: T },
): ServerCell<T> =>
	options?.value !== undefined
		? createCell<T>(options.value)
		: {
				get: () => {
					throw new Error(
						'createSensor(...) has no { value } seed, so it has no server value — seed it, or read it only in a client position.',
					)
				},
				set: () => {},
			}

/** `createState(initial)` → same box as createCell (the v2 name). */
export const createState = <T>(initial: T): ServerCell<T> => createCell(initial)

/**
 * Marks a `ServerCell` as pending (ADR 0024 sub-design 13, async boundaries,
 * LT-012) — never exposed on the type; `isPending` is the only sanctioned way
 * to read it.
 */
const ASYNC_PENDING = Symbol('tsrx-async-pending')

/** Runtime check for an `async` function, without invoking it. */
const isAsyncFunction = (fn: (...args: never[]) => unknown): boolean =>
	(fn as { constructor?: { name?: string } })?.constructor?.name ===
	'AsyncFunction'

/**
 * `deriveCell(fn, options?)` → box over `fn()` evaluated once, UNLESS `fn` is
 * an `async` function (ADR 0024 sub-design 13): the server render is
 * synchronous and never awaits, so an async compute is never invoked at
 * all — calling it would produce a dangling, uncaught Promise. Instead: an
 * `{ initial }` option seeds the retained value directly (the `ok` arm,
 * matching the client's own no-JS-safe seed); otherwise the cell is PENDING
 * at render time (the `nil`/`@pending` arm) — `.get()` throws if read without
 * an `isPending()` guard, same contract a real Task-backed cell enforces.
 * A SYNC compute function's behavior is completely unchanged from before
 * this feature landed — existing non-async `deriveCell` usage (e.g. a
 * `description` memo) is unaffected.
 */
export const deriveCell = <T>(
	compute: () => T | Promise<T>,
	options?: { initial?: T },
): ServerCell<T> => {
	if (!isAsyncFunction(compute as (...args: never[]) => unknown))
		return createCell(compute() as T)
	if (options && 'initial' in options) return createCell(options.initial as T)
	return {
		get: () => {
			throw new Error(
				'deriveCell(...) is pending (no { initial } seed) — read it only inside an isPending()-guarded branch (ADR 0024 async boundaries).',
			)
		},
		set: () => {},
		[ASYNC_PENDING]: true,
	} as ServerCell<T>
}

/**
 * Whether an async-derived cell is pending at render time (ADR 0024 sub-
 * design 13) — `@try`/`@pending`/`@catch` async boundaries route on this,
 * mirroring `@zeix/cause-effect`'s real `isPending()` behaviorally (a
 * different underlying representation server-side, since the server shim
 * never runs the reactive graph).
 */
export const isPending = (signal: unknown): boolean =>
	!!signal &&
	typeof signal === 'object' &&
	(signal as Record<symbol, unknown>)[ASYNC_PENDING] === true

/**
 * `createMemo(fn, options?)` → box over `fn(prev)` evaluated once. Unlike
 * `deriveCell`, `createMemo` has no async overload (cause-effect's `Memo`
 * type is sync-only), so there is no pending-render branch to consider —
 * `options.value` seeds the reducer-pattern `prev` argument on this single
 * server-side call, exactly as it seeds the client's first computation.
 */
export const createMemo = <T>(
	compute: (prev: T | undefined) => T,
	options?: { value?: T },
): ServerCell<T> => createCell(compute(options?.value))

/**
 * `deriveList(fn, options?)` → the same cell-iterating list over `fn()`
 * evaluated once, keyed by `options.keyConfig` as `createList` keys it.
 */
export const deriveList = <T>(
	compute: () => Iterable<T>,
	options?: { keyConfig?: KeyConfig<T> },
): ServerList<T> => createList(compute(), options)

/** `deriveStore(fn)` → box over `fn()` evaluated once. */
export const deriveStore = <T>(compute: () => T): ServerCell<T> =>
	deriveCell(compute)

/**
 * `expose()` records the client interface; on the server it is metadata
 * only — evaluating its argument object (which reads `.get()` once) is the
 * entire effect.
 */
export const expose = (_props: Record<string, unknown>): void => {}

/**
 * Stand-in for a client-only ambient the server render function still
 * has to DECLARE — a `first()`-bound element reference, `host`,
 * `internals` (LT-121). Those name connect-time DOM the server never
 * has, but `expose()`'s argument object is a real expression the
 * generated module evaluates: a component following the
 * children-are-data rule seeds its props by READING the reference
 * (`expose({ value: asNumber(asNumber(0)(input.value)) })`,
 * HOST_PROFILE § data account bullet 2), so an `undefined` stub —
 * what this used to be — made `renderFormSpinbutton()` throw
 * `undefined is not an object` the moment it was called.
 *
 * A self-returning proxy makes any authored chain evaluate harmlessly
 * instead: every property read yields the stub again, calls return it,
 * and coercion yields the empty/zero/false primitive for the hint. The
 * VALUES are meaningless by construction and never reach the markup —
 * `host.<prop>` is never server-known (ADR 0003: the client harvests
 * the real value from the rendered DOM at connect) — so the only
 * contract here is "evaluates without throwing".
 */
export const refStub: any = new Proxy((() => {}) as never, {
	get: (_target, key) => {
		// Coercion and iteration protocols must answer with real
		// callables — returning the stub for `Symbol.toPrimitive` would
		// make `String(stub)` throw "not a function" instead of ''.
		if (key === Symbol.toPrimitive)
			return (hint: string): string | number | boolean =>
				hint === 'number' ? 0 : hint === 'string' ? '' : false
		if (key === Symbol.toStringTag) return 'TsrxRefStub'
		if (key === Symbol.iterator) return function* () {}
		if (key === 'toString' || key === 'valueOf') return () => ''
		// NOT thenable: a stub `then` would make any `await` over it
		// recurse forever resolving itself.
		if (key === 'then') return undefined
		return refStub
	},
	set: () => true,
	has: () => true,
	apply: () => refStub,
	// The target is an arrow function — no own `prototype`, and `length`
	// /`name` are configurable — so reporting no own keys breaks no
	// proxy invariant (a spread over the stub yields `{}`).
	ownKeys: () => [],
	getOwnPropertyDescriptor: () => undefined,
})

/**
 * `defineMethod(fn)` — identity on the server: the branded MethodProducer
 * matters only to the client's `expose()` dispatch, and the method body is
 * never invoked during server evaluation.
 *
 * Constrained to `any[]`, matching the real `@zeix/le-truc` export exactly
 * (`src/types.ts`) — `unknown[]` is stricter than the real signature and
 * rejects a method whose own params have a concrete (non-`unknown`) type
 * under `strictFunctionTypes`' parameter contravariance, e.g. a union type
 * (`(axis: 'l' | 'c' | 'h', big?: boolean) => void`) — found migrating
 * `form-colorgraph.tsrx` (LT-088); every prior `defineMethod` in the corpus
 * happened to use only inferred-`boolean`/no-param callbacks, which
 * apparently didn't trip this.
 */
export const defineMethod = <T extends (...args: any[]) => void>(fn: T): T => fn

/**
 * Parser-factory shims (`asString` etc.). The verbatim setup calls them when
 * `expose()` carries Parser-backed attribute-driven props (ADR 0024
 * sub-design 8); their results are metadata on the server — the real parsers
 * run in the browser at connect time against the host attribute (ADR 0003).
 */
export const asString =
	(fallback: string = '') =>
	(value: string | null | undefined): string =>
		value ?? fallback

export const asInteger =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? Math.trunc(n) : fallback
	}

export const asNumber =
	(fallback: number = 0) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		return value != null && Number.isFinite(n) ? n : fallback
	}

export const asBoolean =
	(fallback: boolean = false) =>
	(value: string | null | undefined): boolean =>
		value == null ? fallback : value !== 'false'

export const asEnum =
	(valid: readonly [string, ...string[]]) =>
	(value: string | null | undefined): string =>
		valid.includes(value as string) ? (value as string) : valid[0]

/** Clamped-integer shim mirroring src/parsers/number.ts (min/max clamp). */
export const asClampedInteger =
	(min: number = 0, max: number = Number.MAX_SAFE_INTEGER) =>
	(value: string | null | undefined): number => {
		const n = Number(value)
		const parsed = value != null && Number.isFinite(n) ? Math.trunc(n) : min
		return Math.max(min, Math.min(parsed, max))
	}

/** JSON shim mirroring src/parsers/json.ts (fallback on null/unparseable). */
export const asJSON =
	<T extends {}>(fallback: T) =>
	(value: string | null | undefined): T => {
		if (value == null || value === '') return fallback
		try {
			return JSON.parse(value) as T
		} catch {
			return fallback
		}
	}

/**
 * HTML-escape interpolated values — same semantics as the docs pipeline's
 * `escapeHtml` (server/templates/utils.ts).
 */
export const esc = (text: string): string =>
	text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;')

/**
 * What a text position renders: the type of every text sink the compiler
 * emits, on the server ({@link text}) and the client (`bindText`), per
 * ADR 0046 s6. Nil renders empty here; on the client it keeps the last
 * value, which on first render is the same empty text.
 */
export type TextValue = string | number | null | undefined

/**
 * The server's text sink: HTML-escape one text position's value.
 *
 * Typed `TextValue` so an object or a boolean reaching a text position is a
 * tsc error at its authored line, through `check:corpus` (ADR 0046 s6) —
 * stringifying it would render `[object Object]` or `true`. To fix one,
 * render a field (`{() => item.get().label}`), or choose the text with a
 * ternary for a boolean (`{() => (done.get() ? 'Done' : 'Open')}`).
 */
export const text = (value: TextValue): string =>
	value == null ? '' : esc(String(value))

/**
 * {@link text} over a thunk's value: the server form of an authored arrow
 * in a text position. The arrow is the argument itself, so tsc reports a
 * non-text return at the arrow's body, on the authored line.
 */
export const textOf = (thunk: () => TextValue): string => text(thunk())

/**
 * Render one attribute from a computed value, matching `bindAttribute`'s
 * client dispatch (string → setAttribute, boolean → toggleAttribute,
 * number → String(v)):
 * - `true`  → ` name` (bare presence)
 * - `false` / `null` / `undefined` → nothing (omitted)
 * - number → ` name="3"` (numbers carry no HTML-escapable characters)
 * - string → ` name="escaped"`
 */
export const attr = (name: string, value: unknown): string => {
	if (value === true) return ` ${name}`
	if (value === false || value === null || value === undefined) return ''
	if (typeof value === 'number') return ` ${name}="${value}"`
	return ` ${name}="${esc(String(value))}"`
}

/**
 * The VALUE one rendered attribute carries, `attr()`'s own dispatch seen
 * from the parser side (LT-386): a connect-time parser never reads the raw
 * expression — it reads the SERIALIZED attribute — so a spliced Parser
 * seed must apply the parser to this, not to the expression's value.
 * `true` → the bare-presence empty string, `false`/`null`/`undefined` →
 * the attribute is absent (null), everything else → its string form.
 */
export const attrValue = (value: unknown): string | null => {
	if (value === true) return ''
	if (value === false || value === null || value === undefined) return null
	return String(value)
}

/**
 * Render a class map's truthy keys as a class list (`{ a: true, b: x }` → `"a"`).
 */
export const cls = (map: Record<string, unknown>): string =>
	Object.entries(map)
		.filter(([, on]) => Boolean(on))
		.map(([token]) => token)
		.join(' ')

/**
 * Render a style map's non-nil entries as an inline style declaration list
 * (`{ color: 'red', '--x': null }` → `"color: red"`), matching `bindStyle()`'s
 * map-form client dispatch (LT-028, LT-029): a `null`/`undefined` value is
 * omitted, same as `removeProperty` on the client. Returns `''` when every
 * entry is nil.
 */
export const styleAttr = (
	map: Record<string, string | null | undefined>,
): string =>
	Object.entries(map)
		.filter(([, v]) => v != null)
		.map(([prop, v]) => `${prop}: ${v}`)
		.join('; ')

/**
 * The `truc:html={expr}` sanitizer is the library's own `sanitizeHtml`
 * (LT-138): the configured default from `configureHtmlSanitizer`, else escape
 * everything — safe but inert. The generated client passes every reactive
 * `truc:html` value through the same function, so both halves share one
 * configuration and one fail-closed default: an unconfigured app renders
 * escaped text on the server AND after hydration, never escaped-then-live.
 * The library still owns no sanitizer (ADR 0010); the consumer configures
 * one — DOMPurify on jsdom here (`createDOMPurify(new JSDOM('').window)`),
 * plain DOMPurify in the browser.
 */
export { configureHtmlSanitizer } from '../../src/bindings'

/**
 * Sanitize HTML for the `truc:html={expr}` dynamic-rendering attribute
 * through the library's `sanitizeHtml`. A `TrustedHTML` result (a sanitizer
 * configured with `RETURN_TRUSTED_TYPE: true` where Trusted Types exist)
 * stringifies to its markup.
 */
export const sanitizeHtml = (html: string): string =>
	String(librarySanitizeHtml(html))

/** `@for` iteration helper over the items themselves (index unused). */
export const items = <T>(iterable: Iterable<T>): T[] => Array.from(iterable)

/** `@for` iteration helper: index/value pairs over any iterable. */
export const entries = <T>(
	iterable: Iterable<T>,
): IterableIterator<[number, T]> => Array.from(iterable).entries()

/**
 * Compose-site `class`/`id` materialization (LT-090) — implemented in
 * `compose-attrs.ts` (markup post-processing, not a signal shim) and
 * re-exported here so generated modules keep a single runtime import.
 */
export { composeHostAttrs } from './compose-attrs'

/** JSON with object keys sorted, so two equal values serialize equal. */
const canonicalJson = (value: unknown): string =>
	JSON.stringify(value, (_key, v: unknown) =>
		v && typeof v === 'object' && !Array.isArray(v)
			? Object.fromEntries(
					Object.entries(v).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
				)
			: v,
	)

/**
 * The client-referenced messages of this render's `t`: argument-less ones
 * as their string, the rest as their parsed AST with the record's
 * `timeZone`/`currency` baked in. A key whose closure carries no AST (a
 * hand-built record in a test) is left out, as is every key whose form
 * equals `source`'s — the preamble's inlined record, which the client
 * falls back to anyway.
 */
const pickClientMessages = (
	t: Readonly<Record<string, unknown>>,
	keys: readonly string[],
	source: Readonly<Record<string, unknown>>,
): Record<string, string | Message> => {
	const picked: Record<string, string | Message> = {}
	for (const key of keys) {
		const value = t[key]
		let form: string | Message | undefined
		if (typeof value === 'string') form = value
		else if (typeof value === 'function') {
			const tagged = (value as { [CLIENT_MESSAGE]?: ClientMessageSource })[
				CLIENT_MESSAGE
			]
			if (tagged) form = bakeMessageEnv(tagged.message, tagged.env)
		}
		if (
			form !== undefined &&
			canonicalJson(form) !== canonicalJson(source[key])
		)
			picked[key] = form
	}
	return picked
}

/**
 * The per-instance `i18n` attribute's value (ADR 0030 s9, LT-218): the
 * client-referenced keys this render's locale changes. Called per render
 * call, so each locale serializes its own messages; a source-locale render
 * usually changes none. Null when nothing is left, which omits the
 * attribute.
 */
export const clientMessages = (
	t: Readonly<Record<string, unknown>>,
	keys: readonly string[],
	source: Readonly<Record<string, unknown>>,
): string | null => {
	const picked = pickClientMessages(t, keys, source)
	return Object.keys(picked).length > 0 ? JSON.stringify(picked) : null
}

/**
 * The render locale, for a root `lang` the component does not render
 * itself (ADR 0030 s6): read off the first client-referenced argument
 * message's record. Emitted only for a component whose client messages
 * format (number, date, plural), so the client's `closest('[lang]')` finds
 * the locale the server folded in even when no ancestor carries it.
 */
export const clientLocale = (
	t: Readonly<Record<string, unknown>>,
	keys: readonly string[],
): string | null => {
	for (const key of keys) {
		const value = t[key]
		if (typeof value !== 'function') continue
		const tagged = (value as { [CLIENT_MESSAGE]?: ClientMessageSource })[
			CLIENT_MESSAGE
		]
		if (tagged) return tagged.env.lang
	}
	return null
}
