/**
 * Typed `.tsrx` compose imports for authored `.tsx`, generated (LT-312).
 *
 * The compiler resolves a `.tsx` parent's compose import of a `.tsrx` child
 * (`imports.ts` accepts both specifiers), but tsc cannot read a `.tsrx`
 * module. The corpus compile therefore writes `tsrx-imports.d.ts` into the
 * output root: one ambient `declare module` per compiled `.tsrx` source,
 * typing its component function through the GENERATED server module's args
 * — the compiled contract itself, so a compose site is checked against the
 * child's real args with no second copy to drift. `examples/tsconfig.json`
 * includes the file. Until LT-312 it was hand-listed (LT-096), one entry
 * added per migration.
 *
 * An ambient pattern matches the import SPECIFIER as written, not the
 * resolved path, so each entry is keyed by the shortest path suffix no other
 * listed source shares: `*\/basic-button.tsrx` while the name is unique, a
 * longer `*\/basic/button/basic-button.tsrx` once two sources share it. Two
 * same-named files never collide on one pattern — the specifier that stops
 * matching is a loud "cannot find module", not a silent mistype.
 */

/* === Types === */

export type TsrxImportSource = {
	/** Authored `.tsrx` path, relative to the project root. */
	source: string
	/** Component function name (`BasicButton`). */
	name: string
	/** Generated server module, relative to the output root. */
	serverModule: string
}

/* === Exported Constants === */

/** The generated typings file, written into the output root. */
export const TSRX_IMPORTS_FILE = 'tsrx-imports.d.ts'

/* === Internal Functions === */

/**
 * The shortest `/`-segment suffix of `source` that no other path equals or
 * ends with. Falls back to the whole path when every suffix is shared —
 * possible only when one root-relative path is a suffix of another.
 */
const uniqueSuffix = (source: string, others: readonly string[]): string => {
	const segments = source.split('/')
	for (let k = 1; k <= segments.length; k++) {
		const suffix = segments.slice(-k).join('/')
		if (!others.some(o => o === suffix || o.endsWith(`/${suffix}`)))
			return suffix
	}
	return source
}

/* === Exported Functions === */

/**
 * The `tsrx-imports.d.ts` text for `sources`, sorted by pattern so the file
 * is stable across compile orders. With no sources it is the header alone:
 * the file always exists, so the tsconfig that includes it never dangles.
 * No top-level `import`/`export` — the file must stay a script for its
 * `declare module` patterns to be ambient.
 */
export const tsrxImportTypings = (
	sources: readonly TsrxImportSource[],
): string => {
	const entries = sources
		.map(entry => ({
			entry,
			pattern: `*/${uniqueSuffix(
				entry.source,
				sources.filter(o => o !== entry).map(o => o.source),
			)}`,
		}))
		.sort((a, b) => a.pattern.localeCompare(b.pattern))
	const lines = [
		'/**',
		' * Generated by the Le Truc corpus compile (LT-312) — DO NOT EDIT.',
		' * Types every compiled `.tsrx` source for compose imports from authored',
		' * `.tsx`, through its generated server module (`tsrx-imports.ts`).',
		' */',
	]
	for (const { entry, pattern } of entries) {
		const module = `./${entry.serverModule.replace(/\.ts$/, '')}`
		lines.push(
			'',
			`declare module '${pattern}' {`,
			`\texport const ${entry.name}: (`,
			'\t\targs: Parameters<',
			`\t\t\ttypeof import('${module}').render${entry.name}`,
			'\t\t>[0],',
			'\t) => JSX.Element',
			'}',
		)
	}
	return `${lines.join('\n')}\n`
}
