/**
 * Typed `.tsrx` compose imports for authored `.tsx`, generated (LT-312).
 *
 * The compiler resolves a `.tsx` parent's compose import of a `.tsrx` child
 * (`imports.ts` accepts both specifiers), but tsc cannot read a `.tsrx`
 * module. The corpus compile therefore writes `tsrx-imports.d.ts` into the
 * output root: one ambient `declare module` per compiled `.tsrx` source,
 * typing its component function through the GENERATED server module's args
 * — the compiled contract itself, so a compose site is checked against the
 * child's real args with no second copy to drift. `examples/tsconfig.json`
 * includes the file. Until LT-312 it was hand-listed (LT-096), one entry
 * added per migration.
 *
 * An ambient pattern matches the import SPECIFIER as written, not the
 * resolved path, so each entry is keyed by the shortest path suffix no other
 * listed source shares: `*\/basic-button.tsrx` while the name is unique, a
 * longer `*\/basic/button/basic-button.tsrx` once two sources share it. Two
 * same-named files never collide on one pattern — the specifier that stops
 * matching is a loud "cannot find module", not a silent mistype.
 *
 * A child with Slot-backed exposed props also gets a `'truc:pass'` key over
 * exactly those props (LT-100) — the `.tsx` host profile's rule that only a
 * pass target declares one, derived from the registry's `exposedProps`
 * instead of hand-declared on the `.tsrx` args. A key the child cannot take
 * (a computed or method prop, a typo) is an excess-property tsc error at
 * the parent's compose site.
 *
 * A tag whose SERVED source is `.tsrx` also gets its `HTMLElementTagNameMap`
 * entry (LT-325): a `.tsx` parent's `first`/`all('<tag>…')` types through
 * the map, and tsc cannot read the `.tsrx` source's own `declare global`.
 * The entry references the generated client's exported props type and the
 * same host type the source declares, so it is IDENTICAL to the client's
 * copy and merges when both are in one program (the root `tsconfig.json`
 * includes every generated client). A tag served from `.tsx` gets none — its
 * authored source carries the entry, under a different props-type symbol,
 * so a second copy would be a TS 2717 mismatch. Until LT-325 the clients
 * themselves were hand-listed in `examples/tsconfig.json` (LT-098/LT-100).
 */

/* === Types === */

export type TsrxImportSource = {
	/** Authored `.tsrx` path, relative to the project root. */
	source: string
	/** Component function name (`BasicButton`). */
	name: string
	/** Generated server module, relative to the output root. */
	serverModule: string
	/** Slot-backed exposed props — the keys a `truc:pass` may replace. */
	passProps?: readonly string[]
}

export type TsrxTagMapEntry = {
	/** Custom element tag (`basic-button`). */
	tag: string
	/** Generated client module, relative to the output root. */
	clientModule: string
	/** The client's exported `<Name>Props` type, when authored. */
	propsType: string | null
	/** `FormAssociatedElement` host instead of `HTMLElement`. */
	formAssociated: boolean
}

/* === Exported Constants === */

/** The generated typings file, written into the output root. */
export const TSRX_IMPORTS_FILE = 'tsrx-imports.d.ts'

/** Where the generated clients import the library from. */
const LIBRARY_IMPORT = '@zeix/le-truc'

/* === Internal Functions === */

/**
 * The shortest `/`-segment suffix of `source` that no other path equals or
 * ends with. Falls back to the whole path when every suffix is shared —
 * possible only when one root-relative path is a suffix of another.
 */
const uniqueSuffix = (source: string, others: readonly string[]): string => {
	const segments = source.split('/')
	for (let k = 1; k <= segments.length; k++) {
		const suffix = segments.slice(-k).join('/')
		if (!others.some(o => o === suffix || o.endsWith(`/${suffix}`)))
			return suffix
	}
	return source
}

/* === Exported Functions === */

/**
 * The `tsrx-imports.d.ts` text for `sources` and `tags`, sorted by pattern
 * and tag so the file is stable across compile orders. With neither it is
 * the header alone: the file always exists, so the tsconfig that includes it
 * never dangles. No top-level `import`/`export` — the file must stay a
 * script for its `declare module` patterns to be ambient and its
 * `HTMLElementTagNameMap` to augment the global one.
 */
export const tsrxImportTypings = (
	sources: readonly TsrxImportSource[],
	tags: readonly TsrxTagMapEntry[] = [],
): string => {
	const entries = sources
		.map(entry => ({
			entry,
			pattern: `*/${uniqueSuffix(
				entry.source,
				sources.filter(o => o !== entry).map(o => o.source),
			)}`,
		}))
		.sort((a, b) => a.pattern.localeCompare(b.pattern))
	const lines = [
		'/**',
		' * Generated by the Le Truc corpus compile (LT-312) — DO NOT EDIT.',
		' * Types every compiled `.tsrx` source for compose imports from authored',
		' * `.tsx`, through its generated server module, and every `.tsrx`-served',
		' * tag for `first`/`all` queries, through its generated client (LT-325;',
		' * `tsrx-imports.ts`).',
		' */',
	]
	if (tags.length > 0) {
		lines.push('', 'interface HTMLElementTagNameMap {')
		for (const entry of [...tags].sort((a, b) => a.tag.localeCompare(b.tag))) {
			const host = entry.formAssociated
				? `import('${LIBRARY_IMPORT}').FormAssociatedElement`
				: 'HTMLElement'
			const module = `./${entry.clientModule.replace(/\.ts$/, '')}`
			const props = entry.propsType
				? ` & import('${module}').${entry.propsType}`
				: ''
			lines.push(`\t${JSON.stringify(entry.tag)}: ${host}${props}`)
		}
		lines.push('}')
	}
	for (const { entry, pattern } of entries) {
		const module = `./${entry.serverModule.replace(/\.ts$/, '')}`
		const pass = [...(entry.passProps ?? [])].sort()
		const passLines =
			pass.length === 0
				? []
				: [
						"\t\t\t'truc:pass'?: {",
						...pass.map(
							prop => `\t\t\t\t${JSON.stringify(prop)}?: JSX.PassEntry`,
						),
						'\t\t\t}',
					]
		lines.push(
			'',
			`declare module '${pattern}' {`,
			`\texport const ${entry.name}: (`,
			'\t\targs: Parameters<',
			`\t\t\ttypeof import('${module}').render${entry.name}`,
			pass.length === 0 ? '\t\t>[0],' : '\t\t>[0] & {',
			...passLines,
			...(pass.length === 0 ? [] : ['\t\t},']),
			'\t) => JSX.Element',
			'}',
		)
	}
	return `${lines.join('\n')}\n`
}
